name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.6
      with:
        path: /home/runner/work/YouTubeFinder/YouTubeFinder/YouTubeFinder.AzureLibrary/bin/Release/netcoreapp3.1/  
